name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main
  push:


#adding comment for diff
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yml
    with:
      area: 'devint'

