name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yml
    with:
      target: 'devint'
  call-workflow-passing-data-qa:
    uses: ./.github/workflows/reusable.yml
    with:
      target: 'qa'
  call-workflow-passing-data-staging:
    uses: ./.github/workflows/reusable.yml
    with:
      target: 'staging'