name: Call a reusable workflow

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps:
      uses: .github/workflows/reusable.yml
      with:
        env: devint
