name: Reusable workflow example

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
           echo "Building on ${{ inputs.target }}"           
      - name: Unit Test
        run: |
           echo "Unit Test on ${{ inputs.target }}"           
      - name: Deployment
        run: |
           echo "Deployment on ${{ inputs.target }}"
